version: '3.8'
services:
  auth:
    build: ../services/auth
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  billing:
    build: ../services/billing
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  catalog:
    build: ../services/catalog
    ports:
      - "8083:8083"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
