version: '3.8'
services:
  auth:
    build: ../services/auth
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

  resource:
    build: ../services/resource
    ports:
      - "8082:8082"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"

